name: Trigger QA Azure Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure QA Pipeline
        run: |
          curl -s -u ":${{ secrets.AZURE_DEVOPS_PAT }}" \
          -X POST \
          -H "Content-Type: application/json" \
          -d "{}" \
          "https://dev.azure.com/Kshitija0716/StellarAI-Automation/_apis/pipelines/10/runs?api-version=7.1"
